import { createLogger } from "../../lib/logger"
import { DEFAULT_SESSION_NAME_RE } from "../../lib/session-title"
import type { AssistantMessage, Message, Part } from "../../lib/types"
import { getProjectClient } from "../../services/connection-manager"
import { deleteSession, getSessionMessages, renameSession } from "../../services/opencode"
import { fallbackModelAtom } from "../fallback-model"
import { messagesFamily } from "../messages"
import { partsFamily } from "../parts"
import { projectModelsAtom } from "../preferences"
import { sessionFamily, upsertSessionAtom } from "../sessions"
import { appStore } from "../store"

const log = createLogger("auto-title-session")

/**
 * Session IDs we've already attempted to auto-title, successfully or not.
 * Guards against double-firing when multiple `message.updated` ticks land
 * for the same completed assistant message, and against ever re-titling a
 * session after the first attempt (even if it somehow still carries an
 * auto-generated-looking name later — e.g. the rename call failed silently).
 */
const attempted = new Set<string>()

const TITLE_MAX_CHARS = 80
const USER_TEXT_MAX_CHARS = 2000
const ASSISTANT_TEXT_MAX_CHARS = 500

/** Joins the text parts of a message into a single plain string. */
function extractText(entry: { info: Message; parts: Part[] } | undefined): string {
	if (!entry) return ""
	return entry.parts
		.filter((p): p is Extract<Part, { type: "text" }> => p.type === "text")
		.map((p) => p.text)
		.join("\n")
		.trim()
}

function normalizeForCompare(s: string): string {
	return s.trim().replace(/\s+/g, " ")
}

/**
 * Whether `title` still looks machine-assigned rather than a deliberate user
 * rename, so it's safe to silently replace.
 *
 * This is broader than just the pristine `"New session - <timestamp>"`
 * default. Verified live against a running OpenCode server: as soon as the
 * first assistant response finishes streaming (well before the message's own
 * `time.completed` fires), the OpenCode server itself renames the session to
 * the raw, untruncated text of the first user message or first assistant
 * response — a naive fallback, not the AI summary this feature provides. By
 * the time our own `message.updated` (completed) hook runs, the title has
 * therefore almost always already been overwritten away from the literal
 * default pattern. Comparing against the actual first-exchange text catches
 * that server-side fallback too, so this feature isn't a no-op in practice.
 */
function isAutoGeneratedTitle(title: string, candidateTexts: string[]): boolean {
	if (DEFAULT_SESSION_NAME_RE.test(title)) return true
	const t = normalizeForCompare(title)
	if (!t) return false
	for (const raw of candidateTexts) {
		const c = normalizeForCompare(raw)
		if (!c) continue
		if (t === c) return true
		// In case OpenCode ever truncates that fallback with a trailing ellipsis.
		const stripped = t.replace(/(\.{3}|…)+$/, "").trim()
		if (stripped && c.startsWith(stripped)) return true
	}
	return false
}

/** Cleans up a raw model reply into a short, presentable session title. */
function sanitizeTitle(raw: string): string | null {
	let title = raw.trim().split("\n")[0]?.trim() ?? ""
	// Strip a leading label the model might add despite instructions (e.g. "Title:").
	title = title.replace(/^title\s*[:\-]\s*/i, "")
	// Strip wrapping quotes (straight and curly).
	title = title.replace(/^["'“”‘’]+|["'“”‘’]+$/g, "")
	// Strip a trailing sentence-ending period.
	title = title.replace(/\.+$/, "")
	title = title.replace(/\s+/g, " ").trim()
	if (!title) return null
	if (title.length > TITLE_MAX_CHARS) title = title.slice(0, TITLE_MAX_CHARS).trim()
	return title
}

function buildTitlePrompt(userText: string, assistantText: string): string {
	return [
		"Summarize the opening exchange of a chat conversation into a short title, 3 to 6 words, plain text, sentence case, no quotes, no trailing period, no markdown.",
		"Reply with ONLY the title and nothing else.",
		"",
		`User: ${userText.slice(0, USER_TEXT_MAX_CHARS)}`,
		assistantText ? `Assistant: ${assistantText.slice(0, ASSISTANT_TEXT_MAX_CHARS)}` : "",
	]
		.filter(Boolean)
		.join("\n")
}

/**
 * Resolves the model to use for the title-generation call: prefer the model
 * that actually produced the just-completed response (always present once an
 * assistant message is complete), then the project's currently-selected
 * model, then the global fallback model. Never hardcodes a specific model —
 * the user may be fully offline/local with no other provider configured.
 */
function resolveModel(
	info: AssistantMessage,
	directory: string,
): { providerID: string; modelID: string } | undefined {
	if (info.providerID && info.modelID) {
		return { providerID: info.providerID, modelID: info.modelID }
	}
	const projectModel = appStore.get(projectModelsAtom)[directory]
	if (projectModel?.providerID && projectModel?.modelID) {
		return { providerID: projectModel.providerID, modelID: projectModel.modelID }
	}
	const fallback = appStore.get(fallbackModelAtom)
	if (fallback?.providerID && fallback?.modelID) {
		return { providerID: fallback.providerID, modelID: fallback.modelID }
	}
	return undefined
}

/**
 * Called from the event processor whenever an assistant message finishes
 * (`message.updated` with `time.completed` set). If this is the session's
 * first completed exchange AND its title still looks machine-assigned (see
 * `isAutoGeneratedTitle`), silently generates a short (3-6 word) AI title and
 * renames the session to it.
 *
 * Entirely best-effort: any failure (no client, no model, generation error,
 * network issue) is logged and swallowed — the session just keeps whatever
 * name it already has, same as before this feature existed. Never surfaces
 * an error to the user, never retries, and never touches the real session's
 * own message transcript (the title call runs in a throwaway child session
 * that's deleted immediately after).
 */
export function maybeAutoTitleSession(info: Message): void {
	if (info.role !== "assistant" || !info.time?.completed) return
	const sessionId = info.sessionID
	if (attempted.has(sessionId)) return

	const entry = appStore.get(sessionFamily(sessionId))
	if (!entry) return

	// First exchange only: exactly one user + one assistant message so far.
	// Checked against the local message store (cheap, already populated by
	// the same event stream) before doing any async work.
	const localMessages = appStore.get(messagesFamily(sessionId))
	const localUserMsgs = localMessages.filter((m) => m.role === "user")
	const localAssistantMsgs = localMessages.filter((m) => m.role === "assistant")
	if (localUserMsgs.length !== 1 || localAssistantMsgs.length !== 1) return

	const localUserText = extractText({
		info: localUserMsgs[0],
		parts: appStore.get(partsFamily(localUserMsgs[0].id)),
	})
	const localAssistantText = extractText({
		info: localAssistantMsgs[0],
		parts: appStore.get(partsFamily(localAssistantMsgs[0].id)),
	})
	if (!isAutoGeneratedTitle(entry.session.title, [localUserText, localAssistantText])) return

	// Lock synchronously, before any `await`, so a second event tick for the
	// same completion can't slip through and fire a competing request.
	attempted.add(sessionId)

	void runAutoTitle(sessionId, entry.directory, info).catch((err) => {
		log.warn("auto-title failed", { sessionId }, err)
	})
}

async function runAutoTitle(
	sessionId: string,
	directory: string,
	info: AssistantMessage,
): Promise<void> {
	const client = getProjectClient(directory)
	if (!client) return

	// Re-fetch the definitive message list from the server rather than trusting
	// local atoms for content — sidesteps any part-ordering race and guarantees
	// we summarize the exact final text.
	const messages = await getSessionMessages(client, sessionId)
	const userEntries = messages.filter((m) => m.info.role === "user")
	const assistantEntries = messages.filter((m) => m.info.role === "assistant")
	if (userEntries.length !== 1 || assistantEntries.length !== 1) return

	const userText = extractText(userEntries[0])
	const assistantText = extractText(assistantEntries[0])
	if (!userText) return

	const model = resolveModel(info, directory)
	if (!model) {
		log.debug("auto-title: no model available, skipping", { sessionId })
		return
	}

	let throwawayId: string | undefined
	try {
		// Throwaway child session: keeps the title-generation exchange out of
		// the real session's transcript entirely. `parentID` also makes the
		// sidebar hide it as a sub-agent for the brief window it exists.
		const created = await client.session.create({
			parentID: sessionId,
			title: "Auto-title",
		})
		throwawayId = created.data?.id
		if (!throwawayId) return

		const result = await client.session.prompt({
			sessionID: throwawayId,
			parts: [{ type: "text", text: buildTitlePrompt(userText, assistantText) }],
			model,
		})
		const rawTitle = (result.data?.parts ?? [])
			.filter((p): p is Extract<Part, { type: "text" }> => p.type === "text")
			.map((p) => p.text)
			.join(" ")
		const title = sanitizeTitle(rawTitle)
		if (!title) return

		// Re-check right before writing: the user may have renamed the real
		// session (or OpenCode's own fallback may have fired again) while this
		// background call was in flight.
		const latest = appStore.get(sessionFamily(sessionId))
		if (!latest || !isAutoGeneratedTitle(latest.session.title, [userText, assistantText])) return

		await renameSession(client, sessionId, title)
		appStore.set(upsertSessionAtom, {
			session: { ...latest.session, title },
			directory: latest.directory,
		})
		log.debug("auto-title: renamed session", { sessionId, title })
	} finally {
		if (throwawayId) {
			try {
				await deleteSession(client, throwawayId)
			} catch (err) {
				log.warn("auto-title: failed to clean up throwaway session", { throwawayId }, err)
			}
		}
	}
}
